sudo: required
dist: trusty

git:
  depth: false

services:
  - docker

env:
  global: 
    - GO111MODULE=on


script:
- if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then make docs; fi

before_deploy:
      make docs

deploy:
  - provider: pages
    edge: false
    github_token: ${GH_TOKEN}
    local_dir: docs/site
    skip_cleanup: true
    on:
      repo: onosproject/onos-docs
      all_branches: true
