sudo: false
language: python
install:
- pip install pygments
- pip install mkdocs
- pip install mkdocs-material
- pip install mkdocs-bootstrap4
script:
- git clean -f -d -x
after_success:
- chmod +x build/build_docs.sh && ./build/build_docs.sh
